name: greenpeace
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  url_launcher_platform_interface: ^1.0.1
  platform_detect: ^1.4.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  screenshot: ^0.2.0
  provider_architecture: ^1.1.1+1
  firebase_core: ^0.4.4+3
  firebase_helpers: ^0.1.8
  firebase_auth: ^0.16.0
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.5
  animated_text_kit: ^2.0.0
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.5+2
  firebase_storage: ^3.1.5
  image_cropper: ^1.2.1
  cached_network_image: ^2.1.0+1
  shared_preferences: ^0.5.7
  photo_view: ^0.9.2
  fluttertoast: ^4.0.1
  firebase_database: ^3.1.3
  firebase_analytics: ^5.0.11
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.1
  url_launcher: ^5.4.5
  table_calendar: ^2.2.3
  folding_cell: ^0.1.2
  align_positioned: ^1.2.5
  eva_icons_flutter: ^2.0.0
  flutter_open_whatsapp: ^0.1.2
  flutter_form_builder: ^3.10.1
  popup_menu: ^1.0.5
  get_it: ^4.0.2
  commons: ^0.7.8+3
  grouped_buttons: ^1.0.4
  splashscreen: ^1.2.0
  flutter_share_me: ^0.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - image/

